// <auto-generated>
//     此文件由 AttributeSetCodeGenerator 从 AttributeSetDefinition 资产生成——请勿手改。
//     自定义逻辑写到同名手写 partial（去掉 .g）。改属性请编辑定义资产后重新生成。
// </auto-generated>
using Likeon.GAS;

namespace Likeon.GAS.Sample.PlayableDemo
{
    [System.Serializable] // AttributeSet 经 [SerializeReference] 落盘需要
    public partial class AS_Health : AttributeSet
    {
        public readonly GameplayAttributeData Health = new GameplayAttributeData(100f);
        public readonly GameplayAttributeData MaxHealth = new GameplayAttributeData(100f);
        public readonly GameplayAttributeData IncomingHealing = new GameplayAttributeData(0f); // Meta
        public readonly GameplayAttributeData IncomingDamage = new GameplayAttributeData(0f); // Meta

        public GameplayAttribute HealthAttribute => GetAttribute(nameof(Health));
        public GameplayAttribute MaxHealthAttribute => GetAttribute(nameof(MaxHealth));
        public GameplayAttribute IncomingHealingAttribute => GetAttribute(nameof(IncomingHealing));
        public GameplayAttribute IncomingDamageAttribute => GetAttribute(nameof(IncomingDamage));

        protected override void RegisterAttributes()
        {
            Register(nameof(Health), Health);
            Register(nameof(MaxHealth), MaxHealth);
            Register(nameof(IncomingHealing), IncomingHealing);
            Register(nameof(IncomingDamage), IncomingDamage);
        }

        public override void PreAttributeChange(GameplayAttribute attribute, ref float newValue)
        {
            if (attribute == HealthAttribute) newValue = UnityEngine.Mathf.Clamp(newValue, 0f, MaxHealth.CurrentValue);
            OnPreAttributeChange(attribute, ref newValue);
        }

        // 手写 partial 里可实现本钩子追加自定义钳制（不用改本生成文件）。
        partial void OnPreAttributeChange(GameplayAttribute attribute, ref float newValue);
    }
}
