// <auto-generated>
//     此文件由 AttributeSetCodeGenerator 从 AttributeSetDefinition 资产生成——请勿手改。
//     自定义逻辑写到同名手写 partial（去掉 .g）。改属性请编辑定义资产后重新生成。
// </auto-generated>
using Likeon.GAS;

namespace Likeon.GAS.Sample.PlayableDemo
{
    [System.Serializable] // AttributeSet 经 [SerializeReference] 落盘需要
    public partial class AS_Poise : AttributeSet
    {
        public readonly GameplayAttributeData Poise = new GameplayAttributeData(3f);
        public readonly GameplayAttributeData MaxPoise = new GameplayAttributeData(3f);
        public readonly GameplayAttributeData PoiseRecover = new GameplayAttributeData(1f);
        public readonly GameplayAttributeData IncomingPoiseDamage = new GameplayAttributeData(0f); // Meta

        public GameplayAttribute PoiseAttribute => GetAttribute(nameof(Poise));
        public GameplayAttribute MaxPoiseAttribute => GetAttribute(nameof(MaxPoise));
        public GameplayAttribute PoiseRecoverAttribute => GetAttribute(nameof(PoiseRecover));
        public GameplayAttribute IncomingPoiseDamageAttribute => GetAttribute(nameof(IncomingPoiseDamage));

        protected override void RegisterAttributes()
        {
            Register(nameof(Poise), Poise);
            Register(nameof(MaxPoise), MaxPoise);
            Register(nameof(PoiseRecover), PoiseRecover);
            Register(nameof(IncomingPoiseDamage), IncomingPoiseDamage);
        }

        public override void PreAttributeChange(GameplayAttribute attribute, ref float newValue)
        {
            if (attribute == PoiseAttribute) newValue = UnityEngine.Mathf.Clamp(newValue, 0f, MaxPoise.CurrentValue);
            OnPreAttributeChange(attribute, ref newValue);
        }

        // 手写 partial 里可实现本钩子追加自定义钳制（不用改本生成文件）。
        partial void OnPreAttributeChange(GameplayAttribute attribute, ref float newValue);
    }
}
