// <auto-generated>
//     此文件由 AttributeSetCodeGenerator 从 AttributeSetDefinition 资产生成——请勿手改。
//     自定义逻辑写到同名手写 partial（去掉 .g）。改属性请编辑定义资产后重新生成。
// </auto-generated>
using Likeon.GAS;

namespace Likeon.GAS.Sample.PlayableDemo
{
    [System.Serializable] // AttributeSet 经 [SerializeReference] 落盘需要
    public partial class AS_Stamina : AttributeSet
    {
        public readonly GameplayAttributeData Stamina = new GameplayAttributeData(100f);
        public readonly GameplayAttributeData MaxStamina = new GameplayAttributeData(100f);

        public GameplayAttribute StaminaAttribute => GetAttribute(nameof(Stamina));
        public GameplayAttribute MaxStaminaAttribute => GetAttribute(nameof(MaxStamina));

        protected override void RegisterAttributes()
        {
            Register(nameof(Stamina), Stamina);
            Register(nameof(MaxStamina), MaxStamina);
        }

        public override void PreAttributeChange(GameplayAttribute attribute, ref float newValue)
        {
            if (attribute == StaminaAttribute) newValue = UnityEngine.Mathf.Clamp(newValue, 0f, MaxStamina.CurrentValue);
            OnPreAttributeChange(attribute, ref newValue);
        }

        // 手写 partial 里可实现本钩子追加自定义钳制（不用改本生成文件）。
        partial void OnPreAttributeChange(GameplayAttribute attribute, ref float newValue);
    }
}
