// Copyright (c) 2026 Likeon. Licensed under the MIT License.
// 属性集代码生成器：从 AttributeSetDefinition 资产单向生成 <类名>.g.cs（只读产物）+ 一次性手写 partial 桩。
// 生成物 = AttributeSet 子类（字段 + Register + 便捷句柄 + 可选钳制）；自定义逻辑写手写 partial，生成器永不覆盖它。
// 入口：AttributeSetDefinition 的 Inspector「生成 C#」按钮，或 AttributeSetCodeGenerator.Generate(def)。

using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Likeon.GAS.Editor
{
    public static class AttributeSetCodeGenerator
    {
        /// <summary>校验定义，返回错误列表（空=通过）。</summary>
        public static List<string> Validate(AttributeSetDefinition def)
        {
            var errors = new List<string>();
            if (def == null) { errors.Add("定义为空"); return errors; }
            if (!IsValidIdentifier(def.ClassName)) errors.Add($"类名不是合法标识符: '{def.ClassName}'");
            if (!IsValidNamespace(def.Namespace)) errors.Add($"命名空间不合法: '{def.Namespace}'");
            if (def.Attributes == null || def.Attributes.Count == 0) errors.Add("至少要有一个属性");

            var seen = new HashSet<string>();
            var names = new HashSet<string>();
            if (def.Attributes != null)
                foreach (var a in def.Attributes)
                    if (a != null && !string.IsNullOrEmpty(a.Name)) names.Add(a.Name);

            if (def.Attributes != null)
            {
                foreach (var a in def.Attributes)
                {
                    if (a == null) continue;
                    if (!IsValidIdentifier(a.Name)) { errors.Add($"属性名不是合法标识符: '{a.Name}'"); continue; }
                    if (!seen.Add(a.Name)) errors.Add($"属性名重复: '{a.Name}'");
                    if (!string.IsNullOrEmpty(a.MaxAttribute) && !names.Contains(a.MaxAttribute))
                        errors.Add($"属性 '{a.Name}' 的 MaxAttribute='{a.MaxAttribute}' 在本集中不存在");
                }
            }
            return errors;
        }

        /// <summary>生成 C#。成功返回生成文件的工程相对路径，失败返回 null（错误已 LogError）。</summary>
        public static string Generate(AttributeSetDefinition def)
        {
            var errors = Validate(def);
            if (errors.Count > 0)
            {
                Debug.LogError($"[AttributeSetCodeGenerator] 生成 '{(def != null ? def.ClassName : "?")}' 失败:\n- " + string.Join("\n- ", errors));
                return null;
            }

            string assetPath = AssetDatabase.GetAssetPath(def);
            string dir = string.IsNullOrEmpty(assetPath) ? "Assets" : Path.GetDirectoryName(assetPath).Replace('\\', '/');
            string genPath = $"{dir}/{def.ClassName}.g.cs";
            string stubPath = $"{dir}/{def.ClassName}.cs";

            File.WriteAllText(genPath, BuildGenerated(def));
            bool wroteStub = false;
            if (!File.Exists(stubPath)) { File.WriteAllText(stubPath, BuildStub(def)); wroteStub = true; }

            AssetDatabase.ImportAsset(genPath);
            if (wroteStub) AssetDatabase.ImportAsset(stubPath);
            AssetDatabase.Refresh();
            Debug.Log($"[AttributeSetCodeGenerator] 已生成 {genPath}" + (wroteStub ? $" + 手写 partial 桩 {stubPath}" : ""));
            return genPath;
        }

        // ---- 生成物（.g.cs，只读） ----
        private static string BuildGenerated(AttributeSetDefinition def)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     此文件由 AttributeSetCodeGenerator 从 AttributeSetDefinition 资产生成——请勿手改。");
            sb.AppendLine("//     自定义逻辑写到同名手写 partial（去掉 .g）。改属性请编辑定义资产后重新生成。");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using Likeon.GAS;");
            sb.AppendLine();
            sb.AppendLine($"namespace {def.Namespace}");
            sb.AppendLine("{");
            sb.AppendLine("    [System.Serializable] // AttributeSet 经 [SerializeReference] 落盘需要");
            sb.AppendLine($"    public partial class {def.ClassName} : AttributeSet");
            sb.AppendLine("    {");

            foreach (var a in def.Attributes)
                sb.AppendLine($"        public readonly GameplayAttributeData {a.Name} = new GameplayAttributeData({F(a.DefaultValue)});"
                    + (a.IsMeta ? " // Meta" : ""));
            sb.AppendLine();

            foreach (var a in def.Attributes)
                sb.AppendLine($"        public GameplayAttribute {a.Name}Attribute => GetAttribute(nameof({a.Name}));");
            sb.AppendLine();

            sb.AppendLine("        protected override void RegisterAttributes()");
            sb.AppendLine("        {");
            foreach (var a in def.Attributes)
            {
                sb.AppendLine($"            Register(nameof({a.Name}), {a.Name});");
                if (a.IsMeta) sb.AppendLine($"            MarkMeta(nameof({a.Name}));"); // meta：防被持续 modifier 误用
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public override void PreAttributeChange(GameplayAttribute attribute, ref float newValue)");
            sb.AppendLine("        {");
            foreach (var a in def.Attributes)
            {
                string expr = ClampExpr(a);
                if (expr != null)
                    sb.AppendLine($"            if (attribute == {a.Name}Attribute) newValue = {expr};");
            }
            sb.AppendLine("            OnPreAttributeChange(attribute, ref newValue);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        // 手写 partial 里可实现本钩子追加自定义钳制（不用改本生成文件）。");
            sb.AppendLine("        partial void OnPreAttributeChange(GameplayAttribute attribute, ref float newValue);");

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        // ---- 手写 partial 桩（只在不存在时生成一次） ----
        private static string BuildStub(AttributeSetDefinition def)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"// {def.ClassName} 的手写 partial：放自定义钳制 / Meta 伤害管线等逻辑。生成器永不覆盖本文件。");
            sb.AppendLine("using Likeon.GAS;");
            sb.AppendLine();
            sb.AppendLine($"namespace {def.Namespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial class {def.ClassName}");
            sb.AppendLine("    {");
            sb.AppendLine("        // 追加自定义钳制（生成的 PreAttributeChange 会调用本方法）：");
            sb.AppendLine("        // partial void OnPreAttributeChange(GameplayAttribute attribute, ref float newValue)");
            sb.AppendLine("        // {");
            sb.AppendLine("        // }");
            sb.AppendLine();
            sb.AppendLine("        // Meta 伤害管线示例（如 IncomingDamage -> -Health），按需取消注释并实现：");
            sb.AppendLine("        // public override void PostGameplayEffectExecute(GameplayEffectModCallbackData data)");
            sb.AppendLine("        // {");
            sb.AppendLine("        // }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string ClampExpr(AttributeSetDefinition.AttributeDef a)
        {
            bool hasMax = !string.IsNullOrEmpty(a.MaxAttribute);
            if (a.ClampMin && hasMax) return $"UnityEngine.Mathf.Clamp(newValue, {F(a.MinValue)}, {a.MaxAttribute}.CurrentValue)";
            if (a.ClampMin) return $"UnityEngine.Mathf.Max({F(a.MinValue)}, newValue)";
            if (hasMax) return $"UnityEngine.Mathf.Min(newValue, {a.MaxAttribute}.CurrentValue)";
            return null;
        }

        private static string F(float v) => v.ToString("R", CultureInfo.InvariantCulture) + "f";

        private static bool IsValidIdentifier(string s)
        {
            if (string.IsNullOrEmpty(s)) return false;
            if (!(char.IsLetter(s[0]) || s[0] == '_')) return false;
            for (int i = 1; i < s.Length; i++)
                if (!(char.IsLetterOrDigit(s[i]) || s[i] == '_')) return false;
            return true;
        }

        private static bool IsValidNamespace(string s)
        {
            if (string.IsNullOrEmpty(s)) return false;
            foreach (var part in s.Split('.'))
                if (!IsValidIdentifier(part)) return false;
            return true;
        }
    }

    [CustomEditor(typeof(AttributeSetDefinition))]
    public class AttributeSetDefinitionEditor : UnityEditor.Editor
    {
        public override void OnInspectorGUI()
        {
            var def = (AttributeSetDefinition)target;
            EditorGUILayout.HelpBox(
                "属性集定义 —— 在此声明属性，点「生成 C#」产出可用的 AttributeSet 类。\n" +
                "本资产是唯一真源；生成的 .g.cs 请勿手改，自定义逻辑写同名手写 partial。",
                MessageType.None);

            DrawDefaultInspector();

            var errors = AttributeSetCodeGenerator.Validate(def);
            if (errors.Count > 0)
                EditorGUILayout.HelpBox("不能生成：\n• " + string.Join("\n• ", errors), MessageType.Warning);

            EditorGUILayout.Space();
            using (new EditorGUI.DisabledScope(errors.Count > 0))
            {
                if (GUILayout.Button($"生成 C#（{def.ClassName}.g.cs）", GUILayout.Height(28)))
                    AttributeSetCodeGenerator.Generate(def);
            }
        }
    }
}
