// Copyright (c) 2026 Likeon. Licensed under the MIT License.
// GameplayTag 常量生成器：从 GameplayTagsSettings 注册表单向生成一个嵌套静态类，
// 让代码用 Game.GameplayTags.Movement.State.Sprint 这种强类型写法替代 RequestTag("Movement.State.Sprint")。
// —— tag 本来就能在编辑器里零代码创建；本生成器只是给「代码端」加类型安全常量，替代手维护的 *Tags.cs。
// 生成物为只读产物；改标签请编辑注册表后重新生成。菜单：Sigil ▸ GAS ▸ Generate Gameplay Tag Constants。

using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Likeon.GAS.Editor
{
    public static class GameplayTagConstantsGenerator
    {
        private const string DefaultNamespace = "Game";
        private const string DefaultClassName = "GameplayTags";

        [MenuItem("Sigil/GAS/Generate Gameplay Tag Constants")]
        public static void GenerateFromMenu() => Generate(DefaultNamespace, DefaultClassName);

        /// <summary>生成常量类。成功返回工程相对路径，失败返回 null（原因已 Log）。</summary>
        public static string Generate(string ns, string className)
        {
            var settings = FindSettings(out string dir);
            if (settings == null)
            {
                Debug.LogError("[GameplayTagConstantsGenerator] 工程里找不到 GameplayTagsSettings 资产——先创建一个并注册标签（Sigil ▸ GAS ▸ Gameplay Tags）。");
                return null;
            }
            if (settings.Count == 0)
            {
                Debug.LogWarning("[GameplayTagConstantsGenerator] 注册表为空，未生成。");
                return null;
            }

            var root = BuildTree(settings.Tags);
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     此文件由 GameplayTagConstantsGenerator 从 GameplayTagsSettings 注册表生成——请勿手改。");
            sb.AppendLine("//     改标签请编辑注册表后重新生成（Sigil ▸ GAS ▸ Generate Gameplay Tag Constants）。");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using Likeon.GAS;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine($"    public static class {className}");
            sb.AppendLine("    {");
            EmitChildren(sb, root, 2);
            sb.AppendLine("    }");
            sb.AppendLine("}");

            string path = $"{dir}/{className}.g.cs";
            File.WriteAllText(path, sb.ToString());
            AssetDatabase.ImportAsset(path);
            AssetDatabase.Refresh();
            Debug.Log($"[GameplayTagConstantsGenerator] 已从 {settings.Count} 个标签生成 {path}");
            return path;
        }

        private static GameplayTagsSettings FindSettings(out string dir)
        {
            dir = "Assets";
            var guids = AssetDatabase.FindAssets("t:GameplayTagsSettings");
            if (guids.Length == 0) return null;
            string p = AssetDatabase.GUIDToAssetPath(guids[0]);
            dir = Path.GetDirectoryName(p).Replace('\\', '/');
            return AssetDatabase.LoadAssetAtPath<GameplayTagsSettings>(p);
        }

        // ---- 建树 ----
        private sealed class Node
        {
            public string FullPath;
            public bool IsTag;
            public readonly SortedDictionary<string, Node> Children =
                new SortedDictionary<string, Node>(System.StringComparer.Ordinal);
        }

        private static Node BuildTree(IReadOnlyList<string> tags)
        {
            var root = new Node();
            foreach (var tag in tags)
            {
                if (string.IsNullOrWhiteSpace(tag)) continue;
                var parts = tag.Split('.');
                var node = root;
                var acc = "";
                foreach (var part in parts)
                {
                    acc = acc.Length == 0 ? part : acc + "." + part;
                    if (!node.Children.TryGetValue(part, out var child))
                    {
                        child = new Node { FullPath = acc };
                        node.Children[part] = child;
                    }
                    node = child;
                }
                node.IsTag = true;
            }
            return root;
        }

        // ---- 生成 ----
        private static void EmitChildren(StringBuilder sb, Node parent, int indent,
            string enclosingTypeName = null, bool hasSelf = false)
        {
            var used = new HashSet<string>();
            // 预留同一类体内已存在的成员名，避免生成冲突：
            //  - 外层类型名本身（成员不能与外围类型同名 → CS0542，如 tag "A.A"）；
            //  - IsTag 节点注入的 Self 成员（子段名恰为 Self 会撞名 → CS0102）。
            if (!string.IsNullOrEmpty(enclosingTypeName)) used.Add(enclosingTypeName);
            if (hasSelf) used.Add("Self");

            foreach (var kv in parent.Children)
            {
                string id = UniqueId(Sanitize(kv.Key), used);
                var node = kv.Value;
                string pad = new string(' ', indent * 4);

                if (node.Children.Count == 0)
                {
                    sb.AppendLine($"{pad}public static readonly GameplayTag {id} = GameplayTag.RequestTag(\"{Escape(node.FullPath)}\");");
                }
                else
                {
                    sb.AppendLine($"{pad}public static class {id}");
                    sb.AppendLine($"{pad}{{");
                    if (node.IsTag)
                        sb.AppendLine($"{pad}    public static readonly GameplayTag Self = GameplayTag.RequestTag(\"{Escape(node.FullPath)}\");");
                    EmitChildren(sb, node, indent + 1, id, node.IsTag);
                    sb.AppendLine($"{pad}}}");
                }
            }
        }

        private static string Sanitize(string seg)
        {
            var sb = new StringBuilder(seg.Length);
            foreach (var c in seg)
                sb.Append(char.IsLetterOrDigit(c) ? c : '_');
            if (sb.Length == 0) sb.Append('_');
            if (char.IsDigit(sb[0])) sb.Insert(0, '_');
            string id = sb.ToString();
            // C# 关键字（class/int/event…）不能直接作标识符 → 加 @ 前缀转成 verbatim 标识符。
            if (CSharpKeywords.IsKeyword(id)) id = "@" + id;
            return id;
        }

        // 转义要嵌进 C# 字符串字面量的标签路径：含 " 或 \ 的 tag 否则会生成不可编译代码。
        private static string Escape(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

        private static string UniqueId(string id, HashSet<string> used)
        {
            string candidate = id;
            int n = 2;
            while (!used.Add(candidate)) candidate = id + "_" + n++;
            return candidate;
        }
    }
}
